name: 'ldm'
#****** Data settings ******
image_size: 256 # resize input images to this size  #128
# pad_channel: 16
resize_size: [256,256]                         #mdf 128,128
img_resize_size: [256,256] 
# cond_path: "/disk/ssy/data/drr/result/split2/zhouguDR" 
# data_path: "/disk/ssy/data/drr/zhougu/zhougunii"
# cond_path: "/disk/ssy/data/drr/result/split2/zhouguDR" 
# data_path: "/disk/ssy/pyproj/bishe/others/zhougujpg"

# cond_path: "/disk/ssy/data/DIAS/myDIAS/ALL_imax_1ch_cond" 
# cond_path: "/disk/ssy/pyproj/bishe/Xray-Diffsuion-main/datas/181conds_512pngs"   #/disk/ssy/data/DIAS/myDIAS/hand/handtesthand_pk
# data_path: "/disk/ssy/pyproj/bishe/Xray-Diffsuion-main/datas/rgb_181_512resize_gray"
cond_path: "/disk/ssy/Xray-Diffsuion-main/datas/mask412_package"   #/disk/ssy/data/DIAS/myDIAS/hand/handtesthand_pk
data_path: "/disk/ssy/Xray-Diffsuion-main/datas/DSA412_nosize_L"
skeleton_path: "/disk/ssy/Xray-Diffsuion-main/datas/skeleton412_512size_flat版"  # 新增：骨架图路径
# cond_path: "/disk/ssy/AAAIresults/Basic-LDM/边缘生成mask打包版"   #/disk/ssy/data/DIAS/myDIAS/hand/handtesthand_pk
# data_path: "/disk/ssy/AAAIresults/Basic-LDM/原DSA256灰"
# skeleton_path: "/disk/ssy/AAAIresults/Basic-LDM/原DSA256灰"  # 新增：骨架图路径


# skeleton_path: None
   
# cond_path: "/disk/ssy/data/drr/result/split/penguDR/" 
# data_path: "/disk/ssy/data/drr/pengu/all/"

output_dir : "./logs/${config.name}"  # the traning logs saved

latent_diffusion:
  # ckpt: True
  # ckpt_path: "/disk/cc/Xray-Diffsuion/logs/ldm/pl_train_ldm-2024-11-08/21-50-19/pl_train_autoencoder-epoch870-val_rec_loss0.00.ckpt"
  # base_learning_rate: 5.0e-5
  # linear_start: 0.0015
  # linear_end: 0.0155
  base_learning_rate: 1.0e-5   #mdf skeleton 7.15
  linear_start: 0.0005
  linear_end: 0.01

  num_timesteps_cond: 1
  high_low_mode: False
  cond_nums: [1]   #[1,2,3]


  log_every_t: 200
  timesteps: 1000
  loss_type: l1  #skeleton    #l1  

  first_stage_key: "image"
  cond_stage_key: "image"

  image_size: 32 #mdf 16
  channels: 4

  cond_stage_trainable: False
  concat_mode: True
  scale_by_std: True
  monitor: 'val/loss_simple_ema'
  lambda_skel: 1 #0.5  #stutaday 16:32 0.5   #1 #0.1
  first_stage_config:
    base_learning_rate: 0.0001
    sync_dist: True
    # params:
    monitor: "val/rec_loss"
    # ckpt_path: "/disk/cc/Xray-Diffsuion/logs/autoencoder/pl_train_autoencoder-2024-10-28/16-40-35-zhougu/pl_train_autoencoder-epoch660-val_rec_loss0.00.ckpt"
    # ckpt_path: "/disk/ssy/Xray-Diffsuion-main/logs/autoencoder/pl_train_autoencoder-2025-04-03/22-43-58/latest.ckpt"
    ckpt_path: "/disk/ssy/Xray-Diffsuion-main/logs/autoencoder/pl_train_autoencoder-2025-04-04/00-43-24/pl_train_autoencoder-epoch349-val_rec_loss0.00.ckpt"
    # ckpt_path: "/disk/ssy/pyproj/bishe/Xray-Diffsuion-main/logs/autoencoder/pl_train_autoencoder-2025-04-02/15-59-54/pl_train_autoencoder-epoch960-val_rec_loss0.00.ckpt" #256 1248
    # ckpt_path: "/disk/ssy/pyproj/bishe/Xray-Diffsuion-main/logs/autoencoder/pl_train_autoencoder-2025-04-04/00-43-24/pl_train_autoencoder-epoch349-val_rec_loss0.00.ckpt"   #0.85
    # ckpt_path: "/disk/ssy/pyproj/bishe/Xray-Diffsuion-main/logs/autoencoder/pl_train_autoencoder-2025-05-14/12-32-29生成mask/pl_train_autoencoder-epoch779-val_rec_loss0.00.ckpt"
    embed_dim: 4
    ddconfig:
      double_z: True
      z_channels: 4
      resolution: 128  #mdf 128
      in_channels: 1
      out_ch: 1
      ch: 128 # 3.23gai mdf32
      ch_mult: [1,2,4,4]  # num_down = len(ch_mult)-1   #1 2 2 2 4  #mdf [1,2,4,4](3.23gai)
      num_res_blocks: 2
      attn_resolutions: []
      dropout: 0.0
    lossconfig:
      disc_start: 10000
      kl_weight: 1.0e-4
      disc_weight: 0.5
      highlow_weight: 0
      high_limit: 0.04
      low_limit: 0.04
      disc_in_channels: 1
      perceptual_weight: 0
  cond_stage_config: 
    cond_type: "pretrained_vit" # pretrained_vit or pretrained_resnet or resnet or vit or unetencoder
    # cond_ckpt_path: "/disk/cyq/2024/pretrained_weights/lvmmed_vit.pth"
    # cond_ckpt_path: "/disk/cyq/2024/pretrained_weights/lvmmed_resnet.torch"
    cond_ckpt_path: "/disk/ssy/Xray-Diffsuion-main/datas/lvmmed_resnet.torch"


  unet_config:
    dims: 2
    image_size: 32 #mdf 16
    in_channels: 12
    out_channels: 4
    model_channels: 192
    attention_resolutions: [1,2,4,8]
    num_res_blocks: 2
    channel_mult: [1,2,3,4]
    num_heads: 8
    use_spatial_transformer: False
    use_scale_shift_norm: True
    resblock_updown: True
    #use_fp16: True

    # context_dim: 4
    transformer_depth: 1
    use_checkpoint: true # save_memory
    legacy: False

  scheduler_config:             #7.25_7.27 no use
    warm_up_steps: [100000]
    cycle_lengths: [10000000000000]
    f_start: [1.e-6]
    f_max: [1.]
    f_min: [1.]


trainer:
  benchmark: True
  # accumulate_grad_batches: 2
  devices: [0]
  # devices: [0]
  accelerator: "auto"
  max_epochs: 1000
  # precision: "bf16-mixed"
  check_val_every_n_epoch: 10
  # strategy: "ddp_find_unused_parameters_true"

