defaults:
  - _self_
  - config: img2img

hydra:
  run:
    dir: ${config.output_dir}/${hydra:job.name}-${now:%Y-%m-%d}/${now:%H-%M-%S}

# overall settings, will be overwrited by the local settings
config:
  num_workers: 8
  seed : False
  batch_size: 1 #7.27 1 #7.25 4 #1
  microbatch: -1
  ema_rate: "0.9999"
  log_interval: 10
  resume_checkpoint: ""
  fp16_scale_growth: 1.0e-3
  weight_decay: 0.0
  save_interval: 10000
  lr: 3.0e-5
  schedule_sampler: "uniform"
  num_samples: 50
  save_img: True
  save_dcm: False
  model_path: "/disk/cyq/2024/My_Proj/med-guided-diffusion/logs/3d/train_diff-2024-04-19/22-14-56/model100000.pt"
  # label_path: "/nvme/ct_reconstruction/label/patient0"
  # source4cond: "/nvme/ct_reconstruction/source/patient0"

  job_name: ${hydra:job.name}
  hydra_path: ${hydra:runtime.output_dir}
  # sample_hydra_path: ${hydra:runtime.sample_out}
  #
  use_neptune: true # False
